global:
  scrape_interval: 3s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: 
        - "localhost:9090"
  - job_name: message_queue
    static_configs:
      - targets: 
        - "host.docker.internal:8080"
  - job_name: rabbitmq-exporter
    static_configs:
      - targets:
        - "host.docker.internal:15692"
  - job_name: nsq-exporter
    static_configs:
      - targets:
        - "host.docker.internal:9117"